site_name: MOOCs MicroPython
site_description: Documentations des cours en ligne MicroPython documentation with Markdown.
site_author: Baptiste Gaultier, Laurent Mattlé

nav:
  - 'Accueil': index.md
  - 'Premiers pas':
    - "L'interface Vittascience": interface.md
    - "La carte Galaxia": galaxia.md
  - 'Guides de référence':
    - 'Contrôle':
        - 'Attendre': 'controle/temps/attendre.md'
        - 'Utiliser le chronomètre': 'controle/temps/chronometre.md'
        - 'Exécuter selon une condition': controle/executer_des_instructions_selon_une_condition.md
        - 'Exécuter selon des conditions': controle/executer_des_instructions_selon_des_conditions.md
        - 'Répéter' : 'boucles/boucle_simple.md'
        - 'Répéter en comptant' : 'boucles/boucle_avec_variable.md'
        - 'Répéter selon des éléments' : 'boucles/boucle_iterative.md'
    - 'Communication': 
      - 'Écrire dans la console': 'communication/ecrire_dans_la_console.md'
    - 'Apparence': 
      - 'Contrôler une LED': 'apparence/led/led.md'
      - "Régler l'intensité lumineuse d'une LED": 'apparence/led/led_pwm.md'
      - 'Contrôler une LED RGB' : 'apparence/led_rgb/led_rgb.md'
    - 'Capteurs':
      - "Détecter l'appui sur un bouton" : 'capteurs/bouton.md'
      - 'Capter la luminosité' : 'capteurs/capteur_lumiere.md'
      - "Capter l'accélération" : 'capteurs/capteur_acceleration.md'
      - 'Capter la distance' : 'capteurs/capteur_ultrasons.md'
      - "Détecter instantanément l'appui sur un bouton" : 'capteurs/bouton_avec_interruption.md'
    - 'Actionneurs': 
      - 'Contrôler un servomoteur' : 'actionneurs/servomoteur.md'
    - 'Opérateur':
      - 'Manipuler des nombres' : 'math/manipuler_des_nombres.md'
      - 'Convertir une valeur dans une autre échelle' : 'math/convertir_une_valeur_dans_une _autre_echelle.md'
    - 'Texte': 'variables/variable_texte.md'
    - 'Variables':
        - 'Stocker du texte': 'variables/variable_texte.md'
        - 'Stocker des nombres': 'variables/variable_nombre.md'
    - 'Listes': 
        - "Créer une liste d'éléments": 'listes/liste_avec_elts.md'
    - 'Fonctions': 'fonctions/fonction.md'
  - 'Annexes':
    - 'La bibliothèque thingz': 
        - 'thingz': 'thingz/thingz.md'
        - 'thingz.accelerometer': 'thingz/thingz_accelerometer.md'
        - 'thingz.compas': 'thingz/thingz_compass.md'
        - 'thingz.button': 'thingz/thingz_button.md'
        - 'thingz.led': 'thingz/thingz_led.md'
        - 'thingz.temperature': 'thingz/thingz_temperature.md'
        - 'thingz.sound': 'thingz/thingz_sound.md'
        - 'thingz.radio': 'thingz/thingz_radio.md'
    - 'Gérer les erreurs': 'try/Gerer_les_erreurs.md'


theme:
    name: material
    language: fr
    logo: img/micropython_isometric_transparent.svg
    favicon: img/favicon.ico
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: green
          accent: green
          toggle:
            icon: material/weather-night
            name: Désactiver le mode nocturne

        # Palette toggle for dark mode
        - scheme: slate
          primary: green
          accent: green
          toggle:
            icon: material/weather-sunny
            name: Activer le mode nocturne
    features:
      - navigation.instant
      - navigation.tracking
      - header.autohide
      - navigation.sections

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - abbr
    - attr_list
    - md_in_html
    - meta
    - tables
    - pymdownx.highlight:
        use_pygments: true
        linenums: true
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        auto_append:
          - docs/includes/abbreviations.md
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js