site_name: MOOCs MicroPython
site_description: Documentations des cours en ligne MicroPython documentation with Markdown.
site_author: Baptiste Gaultier, Laurent Mattlé

nav:
    - Accueil: index.md
    - 'Affichage': 'affichage/led.md'
    - 'Entrées/Sorties': 'entrees_sorties/temps/attendre.md'
    - 'Communication':  'communication/ecrire_dans_la_console.md'
    - 'Réseau': index.md
    - 'Capteurs': index.md
    - 'Actionneurs': 'moteurs/servomoteur.md'
    - 'Logique': index.md
    - 'Boucles':
        - 'Boucle simple': 'boucles/boucle_simple.md'
        - 'Boucle avec variable': 'boucles/boucle_avec_variable.md'
    - 'Math': index.md
    - 'Texte': index.md
    - 'Variables': 
        - 'Stocker du texte': 'variables/variable_chaine_de_caracteres.md'
        - 'Stocker des nombres': 'variables/variable_nombre.md'
    - 'Listes': index.md
    - 'Fonctions': index.md
    
theme:
    name: material
    language: fr
    logo: img/micropython_isometric_transparent.svg
    favicon: img/favicon.ico
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: green
          accent: green
          toggle:
            icon: material/weather-night
            name: Désactiver le mode nocturne

        # Palette toggle for dark mode
        - scheme: slate
          primary: green
          accent: green
          toggle:
            icon: material/weather-sunny
            name: Activer le mode nocturne
    features:
      - navigation.instant
      - navigation.tracking
      - header.autohide

markdown_extensions:
    - toc:
        toc_depth : "1-1"
    - admonition
    - abbr
    - attr_list
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
        linenums: true
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        auto_append:
          - docs/includes/abbreviations.md
    - pymdownx.superfences
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js