site_name: MOOCs MicroPython
site_description: Documentations des cours en ligne MicroPython documentation with Markdown.
site_author: Baptiste Gaultier, Laurent Mattlé

nav:
  - 'Premiers pas':
    - "L'interface Vittascience": index.md
    - "La carte Galaxia": index.md
    - "Le langage MicroPython": index.md
  - 'Guides de référence':
    - 'Affichage': 
      - 'Contrôler une LED': 'affichage/led/led.md'
      - 'Contrôler une LED RVB' : 'affichage/led_rgb/led_rgb.md'
    - 'Entrées/Sorties': 
      - 'Attendre': 'entrees_sorties/temps/attendre.md'
      - 'Utiliser le chronomètre': 'entrees_sorties/temps/chronometre.md'
    - 'Communication': 
      - 'Écrire dans la console': 'communication/ecrire_dans_la_console.md'
    - 'Capteurs': index.md
    - 'Actionneurs': 'moteurs/servomoteur.md'
    - '': index.md
    - 'Logique': 'logique/Instruction_Conditionnelle.md'
    - 'Boucles':
        - 'Boucle simple': 'boucles/boucle_simple.md'
        - 'Boucle avec variable': 'boucles/boucle_avec_variable.md'
    - 'Math': index.md
    - 'Texte': index.md
    - 'Variables': 
        - 'Stocker du texte': 'variables/variable_texte.md'
        - 'Stocker des nombres': 'variables/variable_nombre.md'
    - 'Listes': index.md
    - 'Fonctions': index.md

theme:
    name: material
    language: fr
    logo: img/micropython_isometric_transparent.svg
    favicon: img/favicon.ico
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: green
          accent: green
          toggle:
            icon: material/weather-night
            name: Désactiver le mode nocturne

        # Palette toggle for dark mode
        - scheme: slate
          primary: green
          accent: green
          toggle:
            icon: material/weather-sunny
            name: Activer le mode nocturne
    features:
      - navigation.instant
      - navigation.tracking
      - header.autohide
      - navigation.sections

markdown_extensions:
    - toc:
        toc_depth : "1-1"
    - admonition
    - abbr
    - attr_list
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
        linenums: true
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        auto_append:
          - docs/includes/abbreviations.md
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - css/extra.css

extra_javascript:
  - js/extra.js